#!/usr/bin/env sh

# Set window management approach
yabai -m config layout bsp

# New window spawns to the right if vertical, or bottom if horizontal
yabai -m config window_placement second_child

# Padding between windows
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Mouse support
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise

# Status update
echo "yabai configuration loaded.."
