#!/usr/bin/env bash
# Script to set up Nix Zsh as your shell without changing /etc/shells

set -e

# Get the Nix Zsh path
NIX_ZSH=$(which zsh)

if [[ -z "$NIX_ZSH" ]]; then
  echo "Error: Zsh not found in Nix profile. Please make sure it's installed."
  exit 1
fi

# Create temp directory for config files
TEMP_DIR="$HOME/nix-config-temp"
mkdir -p "$TEMP_DIR"

# Define file paths
ZSH_ENV="$TEMP_DIR/zshenv"
BASH_PROFILE="$TEMP_DIR/bash_profile"
BASHRC="$TEMP_DIR/bashrc"

# Check if we need to set up the config files
echo "Creating configuration files in $TEMP_DIR..."

cat > "$ZSH_ENV" << EOF
# This file was generated by the use-nix-zsh.sh script
# It ensures that your Nix-managed Zsh is used

# Load Nix environment
if [ -e '$HOME/.nix-profile/etc/profile.d/nix.sh' ]; then
  . '$HOME/.nix-profile/etc/profile.d/nix.sh'
fi

# Load Zsh from Nix
export PATH="$HOME/.nix-profile/bin:\$PATH"
EOF

echo "✓ Created $ZSH_ENV"

# Set up bash to exec into zsh
cat > "$BASH_PROFILE" << EOF
# This file was generated by the use-nix-zsh.sh script
# It makes bash exec into zsh automatically

# Source bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
  source "$HOME/.bashrc"
fi

# Automatically switch to zsh if this is an interactive shell
if [ -t 1 ]; then
  NIX_ZSH="$HOME/.nix-profile/bin/zsh"
  if [ -x "\$NIX_ZSH" ]; then
    echo "Switching to Nix Zsh..."
    exec "\$NIX_ZSH" -l
  fi
fi
EOF

echo "✓ Created $BASH_PROFILE"

# Create bashrc update content
cat > "$BASHRC" << EOF
# Added by use-nix-zsh.sh to ensure .bash_profile is loaded
if [ -f "\$HOME/.bash_profile" ]; then
  source "\$HOME/.bash_profile"
fi
EOF
echo "✓ Created $BASHRC"

echo ""
echo "Configuration files created successfully! 🎉"
echo ""
echo "To apply these files, run the following commands:"
echo "  cp $ZSH_ENV $HOME/.zshenv"
echo "  cp $BASH_PROFILE $HOME/.bash_profile"
echo "  echo \"$(cat $BASHRC)\" >> $HOME/.bashrc"
echo ""
echo "After applying these files, your bash shell will automatically switch to Nix Zsh when you log in."
echo "To apply your Nix configuration, run:"
echo "  cd ~/nix-config && ./scripts/rebuild.sh"
echo ""
echo "You'll need to restart your terminal or log out and back in for the changes to take effect."
echo ""
echo "To test the new configuration without logging out, you can run:"
echo "  exec $NIX_ZSH"
echo ""
echo "Would you like to automatically apply these files now? (y/n)"
read -r APPLY
if [[ "$APPLY" =~ ^[Yy]$ ]]; then
  cp "$ZSH_ENV" "$HOME/.zshenv"
  cp "$BASH_PROFILE" "$HOME/.bash_profile"
  echo "$(cat $BASHRC)" >> "$HOME/.bashrc"
  echo "Files applied successfully! You can now run 'exec $NIX_ZSH' to start using zsh."
else
  echo "Files were not applied automatically. You can apply them manually using the commands above."
fi
echo ""