#!/usr/bin/env bash
# Script to set up Nix Zsh as your shell without changing /etc/shells

set -e

# Get the Nix Zsh path
NIX_ZSH=$(which zsh)

if [[ -z "$NIX_ZSH" ]]; then
  echo "Error: Zsh not found in Nix profile. Please make sure it's installed."
  exit 1
fi

# Create zshenv file to set up environment
ZSH_ENV="$HOME/.zshenv"
BASH_PROFILE="$HOME/.bash_profile"
BASHRC="$HOME/.bashrc"

# Check if we need to set up the config files
echo "Setting up your shell to use Nix Zsh..."

cat > "$ZSH_ENV" << EOF
# This file was generated by the use-nix-zsh.sh script
# It ensures that your Nix-managed Zsh is used

# Load Nix environment
if [ -e '$HOME/.nix-profile/etc/profile.d/nix.sh' ]; then
  . '$HOME/.nix-profile/etc/profile.d/nix.sh'
fi

# Load Zsh from Nix
export PATH="$HOME/.nix-profile/bin:\$PATH"
EOF

echo "✓ Created $ZSH_ENV"

# Set up bash to exec into zsh
cat > "$BASH_PROFILE" << EOF
# This file was generated by the use-nix-zsh.sh script
# It makes bash exec into zsh automatically

# Source bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
  source "$HOME/.bashrc"
fi

# Automatically switch to zsh if this is an interactive shell
if [ -t 1 ]; then
  NIX_ZSH="$HOME/.nix-profile/bin/zsh"
  if [ -x "\$NIX_ZSH" ]; then
    echo "Switching to Nix Zsh..."
    exec "\$NIX_ZSH" -l
  fi
fi
EOF

echo "✓ Created $BASH_PROFILE"

# Make sure .bashrc exists and sources bash_profile
if [ ! -f "$BASHRC" ]; then
  cat > "$BASHRC" << EOF
# This file was generated by the use-nix-zsh.sh script
# It ensures .bash_profile is loaded for non-login shells

# Source bash_profile for non-login shells
if [ -f "$HOME/.bash_profile" ]; then
  source "$HOME/.bash_profile"
fi
EOF
  echo "✓ Created $BASHRC"
else
  # Check if .bashrc already sources .bash_profile
  if ! grep -q "source.*bash_profile" "$BASHRC"; then
    echo "" >> "$BASHRC"
    echo "# Added by use-nix-zsh.sh to ensure .bash_profile is loaded" >> "$BASHRC"
    echo "if [ -f \"$HOME/.bash_profile\" ]; then" >> "$BASHRC"
    echo "  source \"$HOME/.bash_profile\"" >> "$BASHRC"
    echo "fi" >> "$BASHRC"
    echo "✓ Updated $BASHRC"
  fi
fi

echo ""
echo "Setup complete! 🎉"
echo ""
echo "Your bash shell will now automatically switch to Nix Zsh when you log in."
echo "To apply your Nix configuration, run:"
echo "  cd ~/nix-config && ./scripts/rebuild.sh"
echo ""
echo "You may need to restart your terminal or log out and back in for the changes to take effect."
echo ""
echo "To test the new configuration without logging out, you can run:"
echo "  exec $NIX_ZSH"
echo ""